import React, { useState } from 'react';
import { AlertTriangle, ShieldAlert, CheckCircle2, Clock, Cpu, User, Monitor, Play, Zap } from 'lucide-react';

export default function IncidentManager({ incidents, setIncidents }) {
  const [filterStatus, setFilterStatus] = useState('ALL');
  const [actionNotice, setActionNotice] = useState(null);

  const handleTriage = (id, newStatus) => {
    setIncidents(prev => prev.map(inc => inc.id === id ? { ...inc, status: newStatus } : inc));
    setActionNotice(`Incident ${id} updated to status: ${newStatus}`);
    setTimeout(() => setActionNotice(null), 3000);
  };

  const handleContainment = (id, actionName, targetName) => {
    setActionNotice(`Playbook executed: [${actionName}] against target [${targetName}] on Incident ${id}. Host isolated / process terminated.`);
    setTimeout(() => setActionNotice(null), 4000);
  };

  const filteredIncidents = incidents.filter(inc => {
    if (filterStatus === 'ALL') return true;
    return inc.status === filterStatus;
  });

  return (
    <div className="space-y-6">
      
      {/* Header Toolbar */}
      <div className="glass-panel rounded-xl p-5 flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <h3 className="font-bold text-slate-100 flex items-center gap-2 text-lg">
            <AlertTriangle className="w-5 h-5 text-rose-500" />
            Security Incident Response Center
          </h3>
          <p className="text-xs text-slate-400 font-mono mt-1">
            Active security tickets generated by the detection engine requiring analyst triage and containment.
          </p>
        </div>

        {/* Filter buttons */}
        <div className="flex items-center gap-2 font-mono text-xs">
          {['ALL', 'NEW', 'IN_PROGRESS', 'RESOLVED'].map(st => (
            <button
              key={st}
              onClick={() => setFilterStatus(st)}
              className={`px-3 py-1.5 rounded-lg border transition-all ${
                filterStatus === st 
                  ? 'bg-cyan-500/20 text-cyan-400 border-cyan-500/40 glow-cyan'
                  : 'bg-slate-900/60 text-slate-400 border-white/5 hover:text-slate-200'
              }`}
            >
              {st}
            </button>
          ))}
        </div>
      </div>

      {/* Containment Action Notification Banner */}
      {actionNotice && (
        <div className="p-4 rounded-xl bg-emerald-500/20 border border-emerald-500/40 text-emerald-400 font-mono text-xs flex items-center gap-2 glow-green animate-in fade-in">
          <Zap className="w-4 h-4" />
          <span>{actionNotice}</span>
        </div>
      )}

      {/* Incident Tickets List */}
      <div className="space-y-4">
        {filteredIncidents.length === 0 ? (
          <div className="glass-panel rounded-xl p-8 text-center text-slate-500 font-mono text-xs">
            No security incidents match status filter '{filterStatus}'.
          </div>
        ) : (
          filteredIncidents.map((inc) => {
            const isCritical = inc.severity === 'CRITICAL';
            const isResolved = inc.status === 'RESOLVED';

            return (
              <div 
                key={inc.id}
                className={`glass-panel rounded-xl p-6 border transition-all ${
                  isCritical && !isResolved ? 'border-rose-500/40 bg-rose-500/5 glow-red' : 'border-white/10'
                }`}
              >
                <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
                  
                  {/* Title & Metadata */}
                  <div className="space-y-2">
                    <div className="flex items-center gap-3 font-mono text-xs">
                      <span className="font-bold text-slate-400">{inc.id}</span>
                      <span className={`px-2 py-0.5 rounded font-bold text-[10px] ${
                        isCritical ? 'bg-rose-500/20 text-rose-400 border border-rose-500/40' : 'bg-amber-500/20 text-amber-400 border border-amber-500/40'
                      }`}>
                        {inc.severity}
                      </span>
                      <span className="px-2 py-0.5 rounded bg-purple-500/20 text-purple-400 border border-purple-500/30 text-[10px]">
                        MITRE: {inc.mitre_id} ({inc.mitre_name})
                      </span>
                      <span className="text-slate-500">{inc.timestamp}</span>
                    </div>

                    <h4 className="font-bold text-base text-slate-100 font-mono">{inc.title}</h4>
                    <p className="text-xs text-slate-300 font-mono">{inc.description}</p>

                    <div className="flex flex-wrap items-center gap-4 text-xs font-mono text-slate-400 pt-2">
                      <span className="flex items-center gap-1.5"><Monitor className="w-3.5 h-3.5 text-cyan-400" /> Host: <strong className="text-slate-200">{inc.hostname}</strong></span>
                      <span className="flex items-center gap-1.5"><User className="w-3.5 h-3.5 text-amber-400" /> User: <strong className="text-slate-200">{inc.user}</strong></span>
                      <span className="flex items-center gap-1.5"><Cpu className="w-3.5 h-3.5 text-purple-400" /> Process: <strong className="text-slate-200">{inc.affected_process} (PID {inc.pid})</strong></span>
                    </div>
                  </div>

                  {/* Actions & Triage Controls */}
                  <div className="flex flex-col sm:flex-row lg:flex-col items-end gap-2 shrink-0 border-t lg:border-t-0 pt-3 lg:pt-0 border-white/5">
                    
                    {/* Triage Status Selector */}
                    <div className="flex items-center gap-1 font-mono text-xs">
                      <button
                        onClick={() => handleTriage(inc.id, 'IN_PROGRESS')}
                        disabled={inc.status === 'IN_PROGRESS'}
                        className={`px-3 py-1 rounded border ${
                          inc.status === 'IN_PROGRESS' ? 'bg-amber-500/20 text-amber-400 border-amber-500/40' : 'bg-slate-900 text-slate-400 border-white/10 hover:text-slate-200'
                        }`}
                      >
                        In Progress
                      </button>
                      <button
                        onClick={() => handleTriage(inc.id, 'RESOLVED')}
                        disabled={inc.status === 'RESOLVED'}
                        className={`px-3 py-1 rounded border ${
                          inc.status === 'RESOLVED' ? 'bg-emerald-500/20 text-emerald-400 border-emerald-500/40' : 'bg-slate-900 text-slate-400 border-white/10 hover:text-slate-200'
                        }`}
                      >
                        Resolve
                      </button>
                    </div>

                    {/* Containment Playbooks */}
                    <div className="flex items-center gap-2 font-mono text-xs mt-1">
                      <button
                        onClick={() => handleContainment(inc.id, 'Kill Process', inc.affected_process)}
                        className="px-2.5 py-1 rounded bg-rose-500/10 hover:bg-rose-500/20 text-rose-400 border border-rose-500/30 transition-all flex items-center gap-1"
                      >
                        <Zap className="w-3 h-3" /> Kill PID {inc.pid}
                      </button>
                      <button
                        onClick={() => handleContainment(inc.id, 'Isolate Host', inc.hostname)}
                        className="px-2.5 py-1 rounded bg-cyan-500/10 hover:bg-cyan-500/20 text-cyan-400 border border-cyan-500/30 transition-all flex items-center gap-1"
                      >
                        <ShieldAlert className="w-3 h-3" /> Isolate Host
                      </button>
                    </div>

                  </div>

                </div>
              </div>
            );
          })
        )}
      </div>

    </div>
  );
}
